<a href="https://colab.research.google.com/github/Pranaam19/Experiments/blob/main/LAb1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity 1
import numpy as np
#
a = np.array([10,20,30,40])
print(a)

b = np.arange(1,11)
print(b)

c = np.linspace(0,1,5)
print(c)



[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#Activity 2

d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

e = np.zeros((3,3))
print(e)

f = np.ones((3,3))
print(f)

g = np.eye(3)
print(g)

A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])
shape = A.shape
print("shape is ",shape)
print(A+B)
print(A-B)
print(A*B)
print(A@B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape is  (2, 2)
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [16]:
#Activity 3

marks = np.array([70,65,80,90,88])

print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))
print(np.std(marks))

78.6
65
90
9.789790600416334


In [25]:
# Take one month (July)  weather data of Udupi
# 1.Hottest and coldest day
# 2.Find monthly avg
# 3.Days reported above 35*c

# weather = np.array([
#   25.3, 25.4, 25.3, 25.5, 25.6, 25.2, 25.1, 25.3, 25.2, 25.1,
#   25.1, 25.1, 25.0, 25.1, 25.2, 25.1, 24.9, 25.1, 24.9, 25.1,
#   25.3, 25.2, 25.0, 24.7, 24.9, 25.0, 25.1, 25.2, 25.0, 25.1,
#   ])
weather1 = np.array([
  25.3, 25.4, 25.3, 25.5, 25.6, 25.2, 25.1, 25.3, 25.2, 25.1,
  25.1, 25.1, 25.0, 25.1, 25.2, 25.1, 24.9, 25.1, 24.9, 25.1,
  25.3, 25.2, 25.0, 24.7, 24.9, 25.0, 25.1, 25.2, 25.0, 25.1,
  ])

print("Hottest day",np.max(weather1),"")
print("Coldest day",np.min(weather1))
avg = np.average(weather1)
print("Avg Temperature",avg)
print("Days above 30*c",np.sum(weather1>30))

Hottest day 25.6
Coldest day 24.7
Avg Temperature 25.136666666666667
Days above 35*c 0


In [28]:
import numpy as np

weather1 = np.array([
  25.1, 26.1, 25.7, 25.5, 24.8, 24.8, 24.6, 26.0, 25.5, 25.7,
    24.5, 26.1, 25.9, 24.9, 24.8, 24.8, 25.0, 25.4, 25.2, 25.0,
    25.5, 24.7, 25.0, 25.1, 25.3, 25.8, 24.8, 25.4, 25.5, 24.6,
    25.5
])

# 1. Hottest and Coldest Days & Dates
max_temp = np.max(weather1)
min_temp = np.min(weather1)

hottest_dates = np.where(weather1 == max_temp)[0] + 1
coldest_dates = np.where(weather1 == min_temp)[0] + 1

print(f"Hottest day: July {hottest_dates[0]} ({max_temp}°C)")
print(f"Coldest day: July {coldest_dates[0]} ({min_temp}°C)")

# 2.Monthly Average
avg = np.mean(weather1)
print(f"Avg Temperature: {avg:.2f}°C")

# 3. Days Reported Above 35°C
days_above_35 = np.sum(weather1 >= 30)
print(f"Days above 35°C: {days_above_35}")


Hottest day: July 2 (26.1°C)
Coldest day: July 11 (24.5°C)
Avg Temperature: 25.25°C
Days above 35°C: 0
